title: Krispi

baseurl: /
url: http://krispi.org

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

future: true

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customi$
date_format: "%-d %b %Y"

lang: id-ID
