title: Krispi
description: Perusahaan konsultan agile di Indonesia. Bergerak seperti (dna.crisp.se/docs/index.html)[Crisp dari Swedia].

# Build settings
markdown: kramdown
theme: jekyll-theme-minimal
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customi$
date_format: "%-d %b %Y"
